// Code generated by mockery v2.10.4. DO NOT EDIT.

package mocks

import (
	entities "github.com/rahulkhairwar/where-got-climbing-gym/entities"
	mock "github.com/stretchr/testify/mock"
)

// MockCoordinatesRepo is an autogenerated mock type for the CoordinatesRepository type
type MockCoordinatesRepo struct {
	mock.Mock
}

// GetAllCoordinates provides a mock function with given fields:
func (_m *MockCoordinatesRepo) GetAllCoordinates() ([]entities.Coordinate, error) {
	ret := _m.Called()

	var r0 []entities.Coordinate
	if rf, ok := ret.Get(0).(func() []entities.Coordinate); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entities.Coordinate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
